export const DATA = [
    {
      id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
      title: 'Ty seš psychopat',
      author: 'Michal Kratejl',
      avatar: './images/michal.jpeg',
      sound: require('../assets/sound/ty-ses-psychopat.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d72',
      title: 'Já nemám čas se tady onanovat do zejtra. Ty vole, dyť jdeme chlastat, nedělej scény.',
      author: 'Michal Kratejl',
      sound: require('../assets/sound/ja-nemam-cas.mp3'),
    },
    {
      id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28bb',
      title: 'Kam si je poslal, ty mladý lidi? Pít! Polož to ty blbče.',
      author: 'Matka',
      sound: require('../assets/sound/kams-je-poslal.mp3'),
    },
    {
      id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f62',
      title: 'A to je ten Jidáš, Ty vole, s kamerou z Kanady.',
      author: 'Igor Chaun',
      sound: require('../assets/sound/a-to-je-ten-jidas.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d73',
      title: 'Máš kameru? Tak ji zašmelíme!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/mas-kameru.mp3'),
    },
    {
      id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28bc',
      title: 'Nejradši mám tady toho černýho skalára. Ten je nadrženej a furt by mrouskal.',
      author: 'Igor Chaun',
      sound: require('../assets/sound/cerny-skalar.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d74',
      title: 'Ja tě tak prokleju! A bude to tak platit...',
      author: 'Matka',
      sound: require('../assets/sound/ja-te-tak-prokleju.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d74q',
      title: 'A nejsi trochu hysterická? Vůbec ne, já jsem svrchovaně nad věcí.',
      author: 'Matka',
      sound: require('../assets/sound/nejsi-hystericka.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d75',
      title: 'A jak se tváří jako debil, já už jsem viděla hodně kameramanů, ale tu držku přiblblou alkoholickou...',
      author: 'Matka',
      sound: require('../assets/sound/a-jak-se-tvari.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d76',
      title: 'Mami, a ty si myslíš, že není dobře, že se trochu napijeme s kamarádama?',
      author: 'Igor Chaun',
      sound: require('../assets/sound/a-mami.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d77',
      title: 'A to je Michal Kratejl, von je vyřízenej!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/a-to-je-michal-kratejl.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d78',
      title: 'Kostky sou vrženyyy!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/kostky-sou-vrzeny.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d79',
      title: 'On se prišel napít!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/on-se-prisel-napit.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7a',
      title: 'Proč si někdy nenajdeš lidi lepší než ty sám?',
      author: 'Igor Chaun',
      sound: require('../assets/sound/proc-si-nekdy-nenajdes.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7s',
      title: 'Tady se kouří, tady se chlastá, tady se rozbíjejí skleničky, tady nemaj co dělat naše obrázky.',
      author: 'Matka',
      sound: require('../assets/sound/tady-se-kouri.mp3'),
    },
    {
      id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
      title: 'Ty taky si pil, ale ty nevypadáš jako debil.',
      author: 'Matka',
      sound: require('../assets/sound/ty-taky-si-pil.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7d',
      title: 'A je pěkně vodulej z toho chlastu.',
      author: 'Michal Kratejl',
      sound: require('../assets/sound/a-je-pekne-vodulej.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7f',
      title: 'Byl jsi na soudě, viděl si tam Helgu. Ta je taky hezká a je primitív.',
      author: 'Matka',
      sound: require('../assets/sound/byl-si-na-soude.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7g',
      title: 'Já sem vypitej.',
      author: 'Igor Chaun',
      sound: require('../assets/sound/ja-sem-vypitej.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7h',
      title: 'Já tě pustím na televizi. To ti nevěřim!',
      author: 'Matka',
      sound: require('../assets/sound/ja-te-pustim.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7j',
      title: 'To je Michal Kratejl, to je můj kamarád, on chlastá, on bejval chytrej, teď dělá plavčíka, protože je vyřízenej.',
      author: 'Igor Chaun',
      sound: require('../assets/sound/kamarad-z-drivejska.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7k',
      title: 'LITRAAANEK!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/litranek.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7l',
      title: 'Mami jak se ti daří? Jsi debil absolutní.',
      author: 'Matka',
      sound: require('../assets/sound/mami-jak-se-ti-dari.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7y',
      title: 'Pětadvacetiletý mladý muž vysokoškolák? Který o sobě říkal, že má nějaký talent, a že je syn umělce? No nezlob se to je tragédie!',
      author: 'Matka',
      sound: require('../assets/sound/petadvacetilety-mlady-muz.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7x',
      title: 'Pozor, tady to začíná!',
      author: 'Matka',
      sound: require('../assets/sound/pozor.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7c',
      title: 'No nezlob se, to je tragédie!',
      author: 'Matka',
      sound: require('../assets/sound/tragedie.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7v',
      title: 'Tvoje žena vaří pochopitelně. No jistě!',
      author: 'Michal Kratejl',
      sound: require('../assets/sound/tvoje-zena-vari.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7b',
      title: 'Že to není pravda? Já bych to nechtěl říkat, ale je to pravda.',
      author: 'Igor Chaun',
      sound: require('../assets/sound/ze-to-neni-pravda.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7n',
      title: 'Znáš to, čím jsme méně inteligetní, tím jsme sebevědomější. No to Michal zná!',
      author: 'Matka',
      sound: require('../assets/sound/znas-to.mp3'),
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d7m',
      title: 'Pojďte dál, pojďte všichni dál. Vyřézenej, ty vole! Nazdar Trosko!',
      author: 'Igor Chaun',
      sound: require('../assets/sound/podte-dal.mp3'),
    },
];
